version: '3'

services:
  aoa_db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sqladmin
      POSTGRES_PASSWORD: password
    volumes:
      - aoa_db_data:/var/lib/postgresql/data

volumes:
  aoa_db_data: