spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shopoo
    username: sqladmin
    password: password
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db_migration
    baseline-on-migrate: true
    enabled: true